services:

  scraper:
    build: .

    container_name: kijiji_scraper_container
    depends_on:
      db_postgres:
        condition: service_healthy

    environment:
      PYTHONUNBUFFERED: 1

  db_postgres:
    image: postgres:latest
    container_name: postgres_db_container
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: database

